### ISSUE TITLE
WIP - Epic: review preservation test

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/cwrc_preservation#6]
Notes gathered from a review of the CWRC preservation run results and possibilities for improvements on commit https://github.com/ualbertalib/cwrc_preservation/commit/4f103a0338bc9c44a394c2a4cf34675d1413091d:

Issues:

* [ ] code on server differs from GitHub

* [ ] deployment documentation and process (align with 2018 May/June Release Management Req, Team Doc Req., and deployment conformity req.)

* [ ] deployment Ansible playbook  (align with 2018 May/June Release Management Req, Team Doc Req., and deployment conformity req.)

* [x] exception handling around to code parsing the CWRC JSON response (test http error) - see commit (https://github.com/ualbertalib/cwrc_preservation/commit/f98181d70a10b6fb108e9dd15dd40ae0a22d9f55) https://github.com/ualbertalib/cwrc_preservation/blob/6de26c7e800a17b3abf575116a838a701fb78185/cwrc_common.rb#L64

* [x] Swift contains several objects reporting a size of zero bytes (e.g., cwrc:725a0ead-690d-4f8b-ba3e-2a96d69a99a5) while in the CWRC repo, the object reports a size. The code creating Swift object does not appear to handle HTTP response codes (4xx and 5xx) which might lead to the Swift objects with a zero size. See commit (https://github.com/ualbertalib/cwrc_preservation/commit/d458d6e7abcf62068d028b217b4e1189fe6640e6) Possible solution: add handling of non 200 HTTP response code - https://github.com/ualbertalib/cwrc_preservation/blob/6de26c7e800a17b3abf575116a838a701fb78185/cwrc_common.rb#L79
https://github.com/ualbertalib/cwrc_preservation/blob/6de26c7e800a17b3abf575116a838a701fb78185/cwrc_preserver.rb#L83
and enhance log message to contain the HTTP response code: https://github.com/ualbertalib/cwrc_preservation/blob/6de26c7e800a17b3abf575116a838a701fb78185/cwrc_preserver.rb#L84

   Example: 
```
   beta.cwrc.ca-access_log:129.128.217.75 - - [30/Apr/2018:15:42:23 -0600] "GET 
   /islandora/object/emic:7efd8668-bbd7-4730-94af-920050000d6d/manage/bagit_extension HTTP/1.1" 
   500 - "-" "Ruby" beta.cwrc.ca 176/176553959
```
* [x] don't save auth token to filesystem
  * (https://github.com/ualbertalib/cwrc_preservation/tree/bugfix/download_issue6)

* [ ] remove from GitHub history connection_cookie.txt

Improvements:

* [ ] could the the cwrc server name be removed from the `secrets.yml` and the `fixtures/vcr_cassettes`? 

* [x] add test where server returns an HTTP error code
  * (https://github.com/ualbertalib/cwrc_preservation/commit/504602941332058f2017f6d528cdd6d420aa9792)

* [x] log file naming: append date so multiple runs don't append (easier to see if error was from current run or prior run)
  * (https://github.com/ualbertalib/cwrc_preservation/commit/1ca99da7c2ea79c617647d63a8d821b8e61742ed)

* [x] prevent auth token saving to current directory of the filesystem
  * (https://github.com/ualbertalib/cwrc_preservation/commit/84c4a4dc7debf73d1ec03c7b43a602752a5e0fc7)

* [x] add working directory to config - avoid clobbering code as the current directory is used as the tmp/working directory
  * (https://github.com/ualbertalib/cwrc_preservation/commit/131a8d8a32ca5ade0f1ea2900f49c2a53bcdf150)

* [x] additional resilience: The HTTP response when requesting an AIP/Bag from CWRC includes in the HTTP header the AIP/Bag's checksum - one could compare this checksum generated on the CWRC side (i.e, CWRC-CHECKSUM) to the received file thus verifying no corruption occurred during transport.
  * see commit (https://github.com/ualbertalib/cwrc_preservation/commit/db7b7b37c68bb004927533499e4b2b8d6af8d739)

* [x] should this line also include a condition where `size=0` at https://github.com/ualbertalib/cwrc_preservation/blob/6de26c7e800a17b3abf575116a838a701fb78185/cwrc_preserver.rb#L75
  * see commit (https://github.com/ualbertalib/cwrc_preservation/commit/db21c60e0db8e83941ca4151faeed32bdf7f6985)

* [x] on failure: replace the current approach of utilizing a filesystem file to record IDs that are reprocessed and replace with logic that compares the CWRC JSON api response (UID + modification date) with the Swift medata (ID, modification date, and AIP/BagIT Bag > 0 size - e.g. `swift list --lh` response) thus reducing complexity of recovering from the failed processing of an UUID 
  * See commits (https://github.com/ualbertalib/cwrc_preservation/commit/17d6c7124bda274d6e7d3d2343fd808fcc7429b3)
(https://github.com/ualbertalib/cwrc_preservation/commit/db21c60e0db8e83941ca4151faeed32bdf7f6985)

* [x] prevent a case of a CWRC PID of `secrets.yml` clobbering config/code files during http download (https://github.com/ualbertalib/cwrc_preservation/blob/phase1/cwrc_common.rb#L86-L88)

* [x] cleanup help `argv.optons` - fix handling of cli help and logging
  * (https://github.com/ualbertalib/cwrc_preservation/commit/1ca99da7c2ea79c617647d63a8d821b8e61742ed)

Blue sky:

* [x] additional resilience: because the timestamp on the CWRC object may change between the generation of the list of objects and the creation of the AIP/Bag, the HTTP response requesting the AIP/Bag includes in the HTTP header response the item's modification timestamp at AIP/Bag creation time. This is minor as the effect is only adding extra downloading or outdated reports if and only if the object changes on the CWRC side between operations on the preservation side.
  * (https://github.com/ualbertalib/cwrc_preservation/commit/43e9387cd68de20db83c338b159daed1f615bf49)

* [ ] perhaps a retry loop if connection to swift fails (e.g., 3 times) https://github.com/ualbertalib/cwrc_preservation/blob/6de26c7e800a17b3abf575116a838a701fb78185/cwrc_preserver.rb#L94

* [ ] add additional user-defined metadata to swift - CWRC collection PID for each object
